// EASP Incident Schema - Phase 6 / Phase 11
// Stores security incidents generated by policy actions, deepfake detection, and DLP violations.

const mongoose = require('mongoose');

const IncidentSchema = new mongoose.Schema({
  incidentId: {
    type: String,
    unique: true,
    sparse: true
  },
  title: {
    type: String,
    required: true
  },
  category: {
    type: String,
    default: 'DLP_VIOLATION'
  },
  severity: {
    type: String,
    required: true,
    enum: ['LOW', 'MEDIUM', 'HIGH', 'CRITICAL'],
    default: 'MEDIUM'
  },
  status: {
    type: String,
    required: true,
    enum: ['OPEN', 'INVESTIGATING', 'RESOLVED', 'DISMISSED'],
    default: 'OPEN'
  },
  source: {
    type: String,
    required: true
  },
  userId: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'User',
    default: null
  },
  username: {
    type: String,
    default: 'anonymous'
  },
  riskScore: {
    type: Number,
    required: true,
    min: 0.0,
    max: 1.0
  },
  riskLevel: {
    type: String,
    required: true,
    enum: ['LOW', 'MEDIUM', 'HIGH', 'CRITICAL']
  },
  contributingFactors: {
    voiceRisk: { type: Number, default: 0.0 },
    socialRisk: { type: Number, default: 0.0 },
    dlpSensitivity: { type: Number, default: 0.0 }
  },
  actionTaken: {
    type: String,
    required: true,
    enum: ['ALLOW', 'REDACT', 'ESCALATE', 'BLOCK']
  },
  auditLogId: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'AuditLog',
    default: null
  },
  notes: [{
    author: String,
    text: String,
    createdAt: { type: Date, default: Date.now }
  }],
  createdAt: {
    type: Date,
    default: Date.now
  },
  resolvedAt: {
    type: Date
  }
});

module.exports = mongoose.model('Incident', IncidentSchema);
